-- 2.3) Implement peer-normalization features: compute specialty-level or DRG-level mean & std, then provider z-scores.
-- 0) Anchor as_of to the latest claim date present
WITH
	M AS (
		SELECT
			MAX(CLAIM_START) AS MAX_DAY
		FROM
			MART.FACT_CLAIM
	)
SELECT
	*
FROM
	M;

-- 1) Inpatient DRG peer stats (365 days), IP (DRG): reimbursement per claim and LOS
-- MS-DRG is the inpatient case-mix/payment grouping used under IPPS, so it’s the right “peer” for IP claims
-- We'll compute 99th percentile per DRG (365d) and cap reimb_amt at that before SD.
DROP TABLE IF EXISTS MART.IP_DRG_CAPS_365;

CREATE TABLE MART.IP_DRG_CAPS_365 AS
WITH
	ASOF AS (
		SELECT
			MAX(CLAIM_START)::DATE AS AS_OF
		FROM
			MART.FACT_CLAIM
	),
	WIN AS (
		SELECT
			DRG,
			PERCENTILE_CONT(0.99) WITHIN GROUP (
				ORDER BY
					REIMB_AMT
			) AS P99
		FROM
			MART.FACT_CLAIM F,
			ASOF
		WHERE
			F.CLAIM_TYPE = 'IP'
			AND F.DRG IS NOT NULL
			AND F.REIMB_AMT IS NOT NULL
			AND F.ADMIT_DT IS NOT NULL
			AND F.DISCHARGE_DT IS NOT NULL
			AND F.CLAIM_START BETWEEN (AS_OF - INTERVAL '365 days') AND AS_OF
		GROUP BY
			DRG
	)
SELECT
	*
FROM
	WIN;

DROP TABLE IF EXISTS MART.IP_DRG_PEER_365;

CREATE TABLE MART.IP_DRG_PEER_365 AS
WITH
	ASOF AS (
		SELECT
			MAX(CLAIM_START)::DATE AS AS_OF
		FROM
			MART.FACT_CLAIM
	),
	IP AS (
		SELECT
			DRG,
			-- cap reimb at DRG p99 (winsorize)
			LEAST(F.REIMB_AMT, COALESCE(C.P99, F.REIMB_AMT)) AS REIMB_WINSOR,
			GREATEST((DISCHARGE_DT - ADMIT_DT), 0)::INT AS LOS_DAYS
		FROM
			MART.FACT_CLAIM F
			LEFT JOIN MART.IP_DRG_CAPS_365 C USING (DRG),
			ASOF
		WHERE
			F.CLAIM_TYPE = 'IP'
			AND F.DRG IS NOT NULL
			AND F.REIMB_AMT IS NOT NULL
			AND F.ADMIT_DT IS NOT NULL
			AND F.DISCHARGE_DT IS NOT NULL
			AND F.CLAIM_START BETWEEN (AS_OF - INTERVAL '365 days') AND AS_OF
	)
SELECT
	DRG,
	AVG(REIMB_WINSOR) AS PEER_REIMB_MEAN_365,
	STDDEV_SAMP(REIMB_WINSOR) AS PEER_REIMB_SD_365,
	AVG(LOS_DAYS) AS PEER_LOS_MEAN_365,
	STDDEV_SAMP(LOS_DAYS) AS PEER_LOS_SD_365,
	COUNT(*) AS PEER_CLAIMS_365
FROM
	IP
GROUP BY
	DRG;

CREATE INDEX IF NOT EXISTS IP_DRG_PEER_365_IDX ON MART.IP_DRG_PEER_365 (DRG);

-- 2) Provider-by-DRG stats and z-scores (365 days)
DROP TABLE IF EXISTS MART.PROVIDER_DRG_STATS_365;

CREATE TABLE MART.PROVIDER_DRG_STATS_365 AS
WITH
	ASOF AS (
		SELECT
			MAX(CLAIM_START)::DATE AS AS_OF
		FROM
			MART.FACT_CLAIM
	),
	PROV AS (
		SELECT
			PROVIDER,
			DRG,
			AVG(LEAST(REIMB_AMT, COALESCE(C.P99, REIMB_AMT))) AS PROV_REIMB_MEAN_365,
			AVG(GREATEST((DISCHARGE_DT - ADMIT_DT), 0))::NUMERIC AS PROV_LOS_MEAN_365,
			COUNT(*) AS PROV_CLAIMS_365
		FROM
			MART.FACT_CLAIM F
			LEFT JOIN MART.IP_DRG_CAPS_365 C USING (DRG),
			ASOF
		WHERE
			F.CLAIM_TYPE = 'IP'
			AND F.DRG IS NOT NULL
			AND F.REIMB_AMT IS NOT NULL
			AND F.ADMIT_DT IS NOT NULL
			AND F.DISCHARGE_DT IS NOT NULL
			AND F.CLAIM_START BETWEEN (AS_OF - INTERVAL '365 days') AND AS_OF
		GROUP BY
			PROVIDER,
			DRG
	)
SELECT
	P.PROVIDER,
	P.DRG,
	P.PROV_CLAIMS_365,
	P.PROV_REIMB_MEAN_365,
	PEER.PEER_REIMB_MEAN_365,
	PEER.PEER_REIMB_SD_365,
	CASE
		WHEN PEER.PEER_REIMB_SD_365 > 0 THEN (P.PROV_REIMB_MEAN_365 - PEER.PEER_REIMB_MEAN_365) / PEER.PEER_REIMB_SD_365
		ELSE NULL
	END AS Z_REIMB_365,
	P.PROV_LOS_MEAN_365,
	PEER.PEER_LOS_MEAN_365,
	PEER.PEER_LOS_SD_365,
	CASE
		WHEN PEER.PEER_LOS_SD_365 > 0 THEN (P.PROV_LOS_MEAN_365 - PEER.PEER_LOS_MEAN_365) / PEER.PEER_LOS_SD_365
		ELSE NULL
	END AS Z_LOS_365
FROM
	PROV P
	JOIN MART.IP_DRG_PEER_365 PEER USING (DRG);

CREATE INDEX IF NOT EXISTS PROVIDER_DRG_STATS_IDX ON MART.PROVIDER_DRG_STATS_365 (PROVIDER, DRG);

-- 3) Outpatient peer stats by primary diagnosis prefix (365 days)
-- Compute p99 per prefix for mild winsorization
DROP TABLE IF EXISTS MART.OP_DXPREFIX_CAPS_365;

CREATE TABLE MART.OP_DXPREFIX_CAPS_365 AS
WITH
	ASOF AS (
		SELECT
			MAX(CLAIM_START)::DATE AS AS_OF
		FROM
			MART.FACT_CLAIM
	)
SELECT
	SUBSTR(DX1, 1, 1) AS DX_PREFIX,
	PERCENTILE_CONT(0.99) WITHIN GROUP (
		ORDER BY
			REIMB_AMT
	) AS P99
FROM
	MART.FACT_CLAIM F,
	ASOF
WHERE
	F.CLAIM_TYPE = 'OP'
	AND F.DX1 IS NOT NULL
	AND F.REIMB_AMT IS NOT NULL
	AND F.CLAIM_START BETWEEN (AS_OF - INTERVAL '365 days') AND AS_OF
GROUP BY
	SUBSTR(DX1, 1, 1);

-- Peer (prefix) means/SDs
DROP TABLE IF EXISTS MART.OP_PREFIX_PEER_365;

CREATE TABLE MART.OP_PREFIX_PEER_365 AS
WITH
	ASOF AS (
		SELECT
			MAX(CLAIM_START)::DATE AS AS_OF
		FROM
			MART.FACT_CLAIM
	)
SELECT
	SUBSTR(DX1, 1, 1) AS DX_PREFIX,
	AVG(LEAST(REIMB_AMT, COALESCE(C.P99, REIMB_AMT))) AS PEER_REIMB_MEAN_365,
	STDDEV_SAMP(LEAST(REIMB_AMT, COALESCE(C.P99, REIMB_AMT))) AS PEER_REIMB_SD_365,
	COUNT(*) AS PEER_CLAIMS_365
FROM
	MART.FACT_CLAIM F
	LEFT JOIN MART.OP_DXPREFIX_CAPS_365 C ON C.DX_PREFIX = SUBSTR(F.DX1, 1, 1),
	ASOF
WHERE
	F.CLAIM_TYPE = 'OP'
	AND F.DX1 IS NOT NULL
	AND F.REIMB_AMT IS NOT NULL
	AND F.CLAIM_START BETWEEN (AS_OF - INTERVAL '365 days') AND AS_OF
GROUP BY
	SUBSTR(DX1, 1, 1);

CREATE INDEX IF NOT EXISTS OP_PREFIX_PEER_IDX ON MART.OP_PREFIX_PEER_365 (DX_PREFIX);

-- Provider-by-prefix means and z
DROP TABLE IF EXISTS MART.PROVIDER_OP_PREFIX_STATS_365;

CREATE TABLE MART.PROVIDER_OP_PREFIX_STATS_365 AS
WITH
	ASOF AS (
		SELECT
			MAX(CLAIM_START)::DATE AS AS_OF
		FROM
			MART.FACT_CLAIM
	)
SELECT
	F.PROVIDER,
	SUBSTR(F.DX1, 1, 1) AS DX_PREFIX,
	COUNT(*) AS PROV_CLAIMS_365,
	AVG(LEAST(F.REIMB_AMT, COALESCE(C.P99, F.REIMB_AMT))) AS PROV_REIMB_MEAN_365,
	PEER.PEER_REIMB_MEAN_365,
	PEER.PEER_REIMB_SD_365,
	CASE
		WHEN PEER.PEER_REIMB_SD_365 > 0 THEN (
			AVG(LEAST(F.REIMB_AMT, COALESCE(C.P99, F.REIMB_AMT))) - PEER.PEER_REIMB_MEAN_365
		) / PEER.PEER_REIMB_SD_365
		ELSE NULL
	END AS Z_REIMB_365
FROM
	MART.FACT_CLAIM F
	LEFT JOIN MART.OP_DXPREFIX_CAPS_365 C ON C.DX_PREFIX = SUBSTR(F.DX1, 1, 1)
	JOIN MART.OP_PREFIX_PEER_365 PEER ON PEER.DX_PREFIX = SUBSTR(F.DX1, 1, 1),
	ASOF
WHERE
	F.CLAIM_TYPE = 'OP'
	AND F.DX1 IS NOT NULL
	AND F.REIMB_AMT IS NOT NULL
	AND F.CLAIM_START BETWEEN (AS_OF - INTERVAL '365 days') AND AS_OF
GROUP BY
	F.PROVIDER,
	SUBSTR(F.DX1, 1, 1),
	PEER.PEER_REIMB_MEAN_365,
	PEER.PEER_REIMB_SD_365;

CREATE INDEX IF NOT EXISTS PROVIDER_OP_PREFIX_IDX ON MART.PROVIDER_OP_PREFIX_STATS_365 (PROVIDER, DX_PREFIX);

-- 4) Final provider-level peer-norm features
DROP VIEW IF EXISTS MART.V_PROVIDER_PEER_NORM_365;

CREATE VIEW MART.V_PROVIDER_PEER_NORM_365 AS
SELECT
	P.PROVIDER,
	-- Inpatient DRG-based z-scores
	SUM(P.PROV_CLAIMS_365) AS IP_CLAIMS_365,
	AVG(NULLIF(Z_REIMB_365, 0)) AS IP_AVG_Z_REIMB_365,
	MAX(Z_REIMB_365) AS IP_MAX_Z_REIMB_365,
	AVG(NULLIF(Z_LOS_365, 0)) AS IP_AVG_Z_LOS_365,
	MAX(Z_LOS_365) AS IP_MAX_Z_LOS_365
FROM
	MART.PROVIDER_DRG_STATS_365 P
GROUP BY
	P.PROVIDER
UNION ALL
SELECT
	O.PROVIDER,
	NULL::BIGINT AS IP_CLAIMS_365,
	NULL::NUMERIC AS IP_AVG_Z_REIMB_365,
	NULL::NUMERIC AS IP_MAX_Z_REIMB_365,
	NULL::NUMERIC AS IP_AVG_Z_LOS_365,
	NULL::NUMERIC AS IP_MAX_Z_LOS_365
FROM
	MART.PROVIDER_OP_PREFIX_STATS_365 O
WHERE
	FALSE;

-- placeholder to keep view definition simple
-- Alternatively: create two separate views (IP and OP), or JOIN them side-by-side:
DROP VIEW IF EXISTS MART.V_PROVIDER_PEER_NORM_365_FULL;

CREATE VIEW MART.V_PROVIDER_PEER_NORM_365_FULL AS
SELECT
	COALESCE(IP.PROVIDER, OP.PROVIDER) AS PROVIDER,
	IP.IP_CLAIMS_365,
	IP.IP_AVG_Z_REIMB_365,
	IP.IP_MAX_Z_REIMB_365,
	IP.IP_AVG_Z_LOS_365,
	IP.IP_MAX_Z_LOS_365,
	-- OP aggregates (across prefixes per provider)
	OP.OP_CLAIMS_365,
	OP.OP_AVG_Z_REIMB_365,
	OP.OP_MAX_Z_REIMB_365
FROM
	(
		SELECT
			PROVIDER,
			SUM(PROV_CLAIMS_365) AS IP_CLAIMS_365,
			AVG(Z_REIMB_365) AS IP_AVG_Z_REIMB_365,
			MAX(Z_REIMB_365) AS IP_MAX_Z_REIMB_365,
			AVG(Z_LOS_365) AS IP_AVG_Z_LOS_365,
			MAX(Z_LOS_365) AS IP_MAX_Z_LOS_365
		FROM
			MART.PROVIDER_DRG_STATS_365
		GROUP BY
			PROVIDER
	) IP
	FULL OUTER JOIN (
		SELECT
			PROVIDER,
			SUM(PROV_CLAIMS_365) AS OP_CLAIMS_365,
			AVG(Z_REIMB_365) AS OP_AVG_Z_REIMB_365,
			MAX(Z_REIMB_365) AS OP_MAX_Z_REIMB_365
		FROM
			MART.PROVIDER_OP_PREFIX_STATS_365
		GROUP BY
			PROVIDER
	) OP USING (PROVIDER);

-- Quick Sanity Checks
-- 1) DRGs with low peer counts (unstable SD → z-scores might be NULL)
SELECT
	DRG,
	PEER_CLAIMS_365
FROM
	MART.IP_DRG_PEER_365
WHERE
	PEER_CLAIMS_365 < 30
ORDER BY
	PEER_CLAIMS_365;

-- consider suppressing z-scores for tiny peer groups
-- 2) Providers with extreme inpatient z-reimb
SELECT
	PROVIDER,
	DRG,
	Z_REIMB_365,
	PROV_CLAIMS_365
FROM
	MART.PROVIDER_DRG_STATS_365
ORDER BY
	Z_REIMB_365 DESC NULLS LAST
LIMIT
	20;

-- 3) Outpatient: top positive z by prefix
SELECT
	PROVIDER,
	DX_PREFIX,
	Z_REIMB_365,
	PROV_CLAIMS_365
FROM
	MART.PROVIDER_OP_PREFIX_STATS_365
ORDER BY
	Z_REIMB_365 DESC NULLS LAST
LIMIT
	20;