-- 4.1) SQL: claim-mix per provider (IP vs OP share)
CREATE MATERIALIZED VIEW IF NOT EXISTS MART.PROVIDER_CLAIM_MIX AS
SELECT
	PROVIDER,
	AVG(
		CASE
			WHEN CLAIM_TYPE = 'IP' THEN 1.0
			ELSE 0.0
		END
	) AS IP_SHARE,
	AVG(
		CASE
			WHEN CLAIM_TYPE = 'OP' THEN 1.0
			ELSE 0.0
		END
	) AS OP_SHARE
FROM
	MART.FEATURES_CLAIM
GROUP BY
	PROVIDER;

-- (Optional) refresh if features_claim was updated
-- REFRESH MATERIALIZED VIEW mart.provider_claim_mix;
ALTER TABLE MART.FEATURES_PROVIDER
ADD COLUMN AVG_REIMB_PER_CLAIM NUMERIC GENERATED ALWAYS AS (
	CASE
		WHEN CLAIMS_30D = 0 THEN NULL
		ELSE REIMB_30D::NUMERIC / CLAIMS_30D
	END
) STORED;




